#pragma once
#define CMD_FIND_MODEL_BY_CHECKSUM 1
#define CMD_SET_OVERLAY 2
#define CMD_GET_VIEWPORT 3
#define CMD_GET_GL_POSITION 4
#define CMD_SET_RESIZEABLE 5
#define CMD_FIND_MODEL_BY_TRIANGLE_COUNT 6
#define CMD_FIND_INVENTORY_FIRST 7
#define CMD_FIND_MODEL_BY_ID2 8
